services:
    imofflinebotdev:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: imofflinebotdev
        volumes:
            - ./data:/app/data
        restart: unless-stopped
